title: Welcome to My Website!
author: Samuel Thomas
email: sthomas313@gatech.edu
description: Personal website
linkedin: https://www.linkedin.com/in/sambthomas/
github: sthomas313-gatech
theme: jekyll-theme-hacker
